name: Build Godot Project

on:
  push: {}

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Export
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Export
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
          relative_project_path: ./
      - name: Create Release
        uses: ncipollo/release-action@v1.18.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.run_number }}-${{ github.sha }}
          artifacts: |
            ${{ steps.export.outputs.build_directory }}/win/*
            ${{ steps.export.outputs.build_directory }}/linux/*
      - name: Upload Pages Artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.export.outputs.build_directory }}/web/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: export
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
