name: Build Godot Project

on:
  push: {}

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Export
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Export
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
          relative_project_path: ./
      - name: Create Release
        uses: ncipollo/release-action@v1.18.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.head_commit.message }}
          artifacts: "${{ steps.export.outputs.build_directory }}/*"
